# Theoretical foundations

## Common Source vs Specific Source Comparison via Information Theory

### Introduction
**Central Goals**

- continue work started by Danica and Peter Vergeer on the analysis of likelihood ratios
- study the differences between specific source (SS) and common source (CS) likelihood ratios (LRs) in an information theoretic way
- does the CS or SS LR have more "information"?
- can be the CS or SS hypotheses (prosecution or defense) be formally compared in terms of being easier to "prove" or "disprove"?

  
**General Notation**
Let $X \in \mathbb{R}^{q_x}$ and $Y \in \mathbb{R}^{q_y}$ be two random vectors with joint distribution $P$ and corresponding density $p$. 


- \textbf{Entropy}: $\mathbb{H}(X) = -\int{p(x) \log p(x) dx}$
- \textbf{Conditional Entropy}: $\mathbb{H}(X|Y) = \mathbb{E}_{Y}\left[-\int{p(x|y) \log p(x|y) dx}\right]$
- \textbf{Type II Conditional Entropy}: $\mathbb{H}_{2}(X|Y) = -\int{p(x|y) \log p(x|y) dx}$
- \textbf{Mutual Information}: $\mathbb{I}(X;Y) = \mathbb{H}(X) - \mathbb{H}(X|Y)$


Proof that Mutual Information is always positive:

\begin{align*}
\mathbb{I}(X;Y) &= \mathbb{H}(X) - \mathbb{H}(X|Y) \\
&= -\int{p(x) \log p(x) dx} + \int{\int{p(x|y)p(y) \log p(x|y) dx} dy} \\
&= -\int{\int{p(x,y) \log p(x) dx}dy} + \int{\int{p(x,y) \log p(x|y) dx} dy} \\
&= -\int{\int{p(x,y) \log p(x) dx}dy} + \int{\int{p(x,y) \log \frac{p(x,y)}{p(y)} dx} dy} \\
&= \int{\int{p(x,y) \log \frac{p(x,y)}{p(x)p(y)} dx}dy} \\
&= KL(P||P_{X} \times P_{Y}) \\
&\geq 0
\end{align*}
  
### Common Source vs Specific Source LR
The "common source" problem is to determine whether two pieces of evidence, both with unknown origin, have the same origin. One might be interested in this problem if two crimes were suspected to be linked, but no suspect has yet been identified. Alternatively, the "specific source" problem is to determine whether a fragment of evidence coming from an unknown source, such as evidence at a crime scene, has the same origin as a fragment of evidence of known origin, such as evidence collected directly from a suspect.

**Basic Setup**

- $H \in \{ H_p, H_d \}$ as the random variable associated with the CS hypothesis. 
- $A$ and $B$ are discrete r.v.'s representing two "sources" of evidence
- distributions for $A$ and $B$ defined conditionally based on the hypothesis
- SS hypothesis is represented by the conditional random variable $H_p|A$
- $X$ is data coming from $A$, $Y$ is data coming from $B$
- compare information contained in $(X,Y)$ about $H_p$ and $H_p|A$
- join density can be written as $p(X,Y,A,B,H) = p(X,Y|A,B)p(B|A,H)p(A|H)p(H)$

**Is there more information in a CS or SS LR?**

Let us examine this question in two different ways. 

1. Is the posterior entropy (given $(X,Y)$) in the common source hypothesis smaller than that of the specific source hypothesis?
     + In other words, would observing the specific value of $A$ as well as the data make you _more_ certain about $H$ than just observing the data?
2. Is the posterior entropy (given $(X,Y)$) in the common source hypothesis smaller than the average (over possible values for $(X,Y,A)$) posterior entropy of the specific source hypothesis?
     + In other words, do you expect that, on average, observing the value of $A$ as well as the data make you _more_ certain about $H$ than just observing the data?

Answering the first question/interpretation, to me, requires proving that 

\[ \mathbb{H}_{2}(H|X,Y) - \mathbb{H}_{2}(H|X,Y, A) \geq 0 \].

Answering the second question requires proving that 

\[ \mathbb{H}(H|X,Y) - \mathbb{H}(H|X,Y, A) \geq 0 \].

\noindent Luckily, the second question is true due to the fact that 

\begin{align*}
\mathbb{H}(H|X,Y) - \mathbb{H}(H|X,Y,A) &= \mathbb{E}_{(X,Y)} \left[ - \int{p(h,a|x,y) \log p(h|x,y) d(h,a)} + \int{p(h,a|x,y) \log p(h|x,y,a) d(h,a)} \right] \\
&= - \int{p(h,a|x,y)p(x,y) \log \frac{p(h,a|x,y)}{p(a|x,y)p(h|x,y)} d(h,x,y,a)} \\
&= \mathbb{E}_{(X,Y)} \left[ KL(P_{(H,A)|(X,Y)}||P_{H|(X,Y)} \times P_{A|(X,Y)}) \right] \geq 0
\end{align*}

Whether or not $\mathbb{H}_{2}(H|X,Y) - \mathbb{H}_{2}(H|X,Y, A) \geq 0$ is not obvious. We have that 

\begin{align*}
\mathbb{H}_{2}(H|X,Y) - \mathbb{H}_{2}(H|X,Y, A) &= \int{-p(h|x,y)\log p(h|x,y) dh} - \int{-p(h|x,y,a) \log p(h|x,y,a) dh} \\
&=  \frac{p(a)}{p(a|x,y)}\int{-p(h|x,y,a)\log p(h|x,y) dh} + \int{p(h|x,y,a) \log p(h|x,y,a) dh}\\ 
&???
\end{align*}

We can try and understand the value of $\mathbb{H}_{2}(H|X,Y) - \mathbb{H}_{2}(H|X,Y, A)$ in terms of $\frac{p(a)}{p(a|x,y)}$. For example, if $\frac{p(a)}{p(a|x,y)} \geq 1$, then $\mathbb{H}_{2}(H|X,Y) - \mathbb{H}_{2}(H|X,Y, A) \geq 0$. If $\frac{p(a)}{p(a|x,y)} \leq 1$, then it is hard to say much about the value of $\mathbb{H}_{2}(H|X,Y) - \mathbb{H}_{2}(H|X,Y, A)$.

### Other notions of information
- Information in $Y$ about $X$:
    - $\int{p(x|y) \log \frac{p(x|y)}{p(x)} dx}$
    - nonnegative
    - Equal to zero when $X \perp Y$
    - needn't integrate over $Y$ (?)
    - as opposed to entropy, information in a random variable requires another random variable to be "predicted"... this is fine in our situation as we have a natural candidate: $H_p$ or $H_d$

## Score-based Likelihood Ratios are not Fundamentally "Incoherent"
Concern has been raised in the literature on LRs about a desirable property supposedly inherently absent from specific-source SLRs. The property, dubbed "coherence", intuitively says that given two mutually exhaustive hypotheses, $H_A$ and $H_B$, the likelihood ratio used to compare hypothesis A to hypothesis B should be the reciprocal of that used to compare hypothesis B to hypothesis A. I will argue that the claims about the inherent incoherency of SLRs is a result of thinking about SLRs too narrowly. Specifically, I will show that the arguments as to why SLRs are incoherent arise through the inappropriate comparison of SLRs based on different score functions. When one appropriately considers a single score function, incoherency is impossible. 

### Coherence
Denote by $E \in \mathbb{R}^{n}$ the vector of random variables describing _all_ of the observed evidence or data which will be used to evaluate the relative likelihood of the two hypotheses. Define by $LR_{i,j} \equiv \frac{p(E|H_i)}{p(E|H_j)}$ the likelihood ratio of hypothesis $i$ to hypothesis $j$. The coherency principal is satisfied if 

\[ LR_{i,j} = \frac{1}{LR_{j,i}} \].

Likelihood ratios are fundamentally coherent, but what about score-based likelihood ratios? Denote by $s: \mathbb{R}^n \rightarrow \mathbb{R}^{q}$ a score function mapping the original data to Euclidean space of dimension $q$ (typically $q = 1$). Similar to LRs, denote by $SLR_{i,j} \equiv \frac{p(s(E)|H_i)}{p(s(E)|H_j)}$ the score-based likelihood ratio comparing hypothesis $i$ to hypothesis $j$. Clearly, in this general context SLRs are also coherent.

### Problems with arguments showing SLRs are incoherent
Let us examine the arguments presented in [REFS] to the incoherence of SLRs. These arguments stem from an example where there are two known sources of evidence say, source $A$ and source $B$, each producing data $e_A$ and $e_B$, respectively. Furthermore, assume that we have a third piece of evidence of unknown origin, $e_u$, which must have come from either $A$ or $B$. We then wish to evaluate the support of the data for $H_A$ or $H_B$ defined as follows 

$$\begin{array}{cc}
H_A: & e_u \text{ was generated from source } A \\
H_B: & e_u \text{ was generated from source } B.
\end{array}$$

In this case, we have $LR_{A,B} = \frac{p(e_A, e_B, e_u|H_A)}{p(e_A, e_B, e_u|H_B)}$. We make use of _all_ available data in the formulation of the numerator and denominator densities. Under the assumptions that each fragment of evidence is independent under both hypothesis $A$ and $B$ as well as that $p(e_A,e_B|H_A) = p(e_A,e_B|H_B)$, the LR reduces to $LR_{A,B} = \frac{p(e_u|H_A)}{p(e_u|H_B)}$. The second assumption is generally acceptable as the source of $e_u$ ought to have no impact on the distribution of the evidence with known source.

[REFS] then consider possible SLRs for this example. However, they make an assumption that the score is explicitly a function only of two fragments of evidence. That is, assuming the dimension of $e_i$, $dim(e_i) = k$, is constant for $i = A,B,u$, their score maps $s:\mathbb{R}^k \times \mathbb{R}^k \rightarrow \mathbb{R}$. An common example of such a score is Euclidean distance, i.e. $s(x,y) = \left[ \sum_{i = 1}^{k}(x_i - y_i)^2 \right]^{1/2}$. Such a score makes perfect sense in a typical specific-source problem context in which only two fragments of evidence are considered: one from the known source and one from the unknown source. 

However, when one desires to create an SLR based on this score in this particular example, it is tempting to suggest that the natural SLR is $SLR_{A,B} = \frac{p(s(e_A,e_u)|H_A)}{p(s(e_A,e_u)|H_B)}$. Yet, the natural SLR if the hypotheses were reversed is $SLR_{B,A} = \frac{p(s(e_B,e_u)|H_B)}{p(s(e_B,e_u)|H_A)}$. Neither of these SLRs is the reciprocal of the other, and so the specific source SLR appears to be "incoherent". 

This approach, however, should raise a red flag immediately. Why, in the full LR case, do we require that (simplifying model assumptions aside) the numerator and denominator densities be functions of all available data, but the score is not? Furthermore, if we consider these SLRs in the more general context of scores depending on all available data, we see that, in fact, what [REFS] define to be $SLR_{A,B}$ and $SLR_{B,A}$ turn out to be two different SLRs depending on two different scores. 

For clarity, we will use $s(\cdot)$ to denote scores which are explicitly functions of _all_ observed data, and we will use $\delta (\cdot)$ to denote score functions which are only a function of two fragments of evidence/data. Specifically, the score in $SLR_{A,B}$ is $s_1(e_u,e_A,e_B) = \delta(e_u,e_A)$ and the score in $SLR_{B,A}$ is $s_2(e_u,e_A,e_B) = \delta(e_u,e_B)$. While the functional form of the score in the two SLRs _appears_ to be the same, clearly $s_1(e_u,e_A,e_B) \neq s_2(e_u,e_A,e_B)$. Thus, the two SLRs are simply two distinct quantities whose relationship needn't be expected to be related anymore than if one had decided to use two different function forms of $\delta(\cdot,\cdot)$ in the two separate SLRs. 

One might ask how to reasonably construct an SLR which utilizes a (univariate) score other than a similarity metric for two fragments of evidence. One such example in this case would be $s(e_u, e_A, e_B) = \frac{\delta(e_u,e_A)}{\delta(e_u,e_B)}$. Intuitively, under $H_A$, the numerator should be larger than the denominator, while under $H_B$, the opposite should be true. 

### Example of a coherent SLR in the two source problem
Suppose that our hypotheses are defined such that 

$$\begin{array}{cc}
H_A: & e_u \sim N(\mu_A, \sigma^2), e_A \sim N(\mu_A, \sigma^2), e_B \sim N(\mu_B, \sigma^2) \\
H_B: & e_u \sim N(\mu_B, \sigma^2), e_A \sim N(\mu_A, \sigma^2), e_B \sim N(\mu_B, \sigma^2),
\end{array}$$

where $e_u$, $e_A$, $e_B$ are mutual independent under both $H_A$ and $H_B$. 

### Other Possible Viewpoints?
I have assumed in the previous section that the order of consideration of hypotheses should not affect the ordering of the data vector $E = (e_u,e_A,e_B)$ or of the ordering of these arguments to the score function. This seems reasonable, but perhaps [REFS] would argue that considering $H_A$ first, $E = (e_u, e_A, e_B)$ and $s(E) = s(e_u, e_A, e_B)$, but considering $H_B$ first, $E = (e_u, e_B, e_A)$ and $s(E) = s(e_u, e_B, e_A)$. In this case, $SLR_{A,B} \neq \frac{1}{SLR_{B,A}}$ because we switch the order of arguments to the score from one SLR to the other. Note that, however, if we relax the independence assumptions of independence under either $H_A$ or $H_B$, then even the LR becomes "incoherent" because $\frac{p(e_u, e_A, e_B|H_A)}{p(e_u, e_A, e_B|H_B)} \neq \frac{p(e_u, e_B, e_A|H_A)}{p(e_u, e_B, e_A|H_B)}$ in general.

It is true that the LR depends only on the evidence of the unknown source _in this specific scenario_, but that is a consequence of modeling assumptions and not of LR paradigmatic principals. 