# Project IMPL: Implementation and Practice {#impl}

## Demonstrative Evidence and Firearms

Project purpose

1. Examine the use of demonstrative (picture) evidence in examiner testimony
2. Develop and test language for quantitative firearms analysis testimony
3. Validate quantitative language for firearms analysis with and without demonstrative evidence

### Previous work

The FRStat program produces a probability that a fingerprint was created by the 
subject, as opposed to being produced by a different source. This language was 
investigated in Garrett et al.'s "Comparing Categorical and Probabilistic 
Fingerprint Evidence" (2018). Garrett et al. found that there was no significant
difference in conviction rates between simple match language and the strongest
(as well as the weakest) probability language. In terms of the likelihood that 
the defendant committed the crime, Garrett et al. found that the lowest probability 
condition (the probability being 10 times greater for the subject versus a different 
source) was significantly different from the highest probability condition (1,000,000 
times greater). However, there was not a significant difference between the lowest 
probability and the next highest probability (10,000 times greater).

### Study Design

This study design is a 2x2x3 factorial. The first factor is the presence or
absence of demonstrative evidence. The second factor is the presence or absence of
the bullet matching algorithm, and the third factor is the expert's conclusion:
match, inconclusive, or not a match.

### Sample Testimony

Two different expert testimonies have been drafted. The first testimony is that
of the firearms examiner. This testimony relates specifically to the case used in
the study.The second testimony is that of the algorithm expert. This testimony
relates to the details of how the algorithm works, as well as when it may be used.

#### Firearms Examiner

The firearms examiner's testimony includes a description of how bullets are marked, 
as well as how the expert examines the bullets using a comparison microscope. The
examiner then concludes that the bullets either match, do not match, or are inconclusive.

Demonstrative evidence for this section would include: an image of barrel rifling, 
an image of a fired bullet, and an image of two bullets aligned using a comparison 
microscope.

When the bullet matching algorithm is included in the testimony, the firearms
expert would describe their experience with the algorithm, as well as a simple
description of the algorithm and the score it produces. This score should generally 
correspond to the examiner's conclusion. Demonstrative evidence would include
an image of the land-to-land scores.

#### Algorithm Expert

The algorithm expert's testimony includes a more in-depth description of how the
algorithm works: finding lands, extracting signatures, and comparing signatures
to produce a score. It also includes information about how the algorithm has
been tested, as well as the validity of using the algorithm for the case in question.

Demonstrative evidence for this section would include: an image of how lands can
be located, and an image of the comparison of two signatures.